# Generated by Django 2.2.4 on 2019-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
