# Generated by Django 2.2.4 on 2019-10-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stms_app', '0003_auto_20191002_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_pwd',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='student_pwd',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
